name: CICD Workflow

on:
  release:
    types:
      - created
  workflow_dispatch: {}
  push:

jobs:
  cicd:
    name: cicd
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      ENV: dev
      TAG: latest
      PYTHON_VERSION: 3.8

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.0.2
      - name: Install python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
